### PR TITLE
[Delivers #112691701] hiptest-publisher tag filter (v1)

### PR DESCRIPTION
**Pull request by mhfrantz**
Replaces #1 and #2 but with a different PT chore.

### CODE REVIEW

**Comment by mhfrantz** [comment]
If the Unitive-specific examples are inappropriate for a public repo, I can refactor them.  Or we can just take this whole repo private and never look back.

**Comment by ghost** [comment]
We probably just want our own fork for this. At least for the `make` and Docker bits, because I think their toolchain includes non-cygwin Windows.

**Comment by ghost** [comment]
looks good. One comment.

FTP

**Comment by mhfrantz** [comment]
PTAL

**Comment by ghost** [comment]
LGTM
Shall I squash anything?

…
edit:  Nah.  Merging.

**Pull request merged**
